### ISSUE TITLE
how/where do i use this

### ISSUE THREAD

**Issue by nonchip** [tinwatchman/Responsive5e-Dynamic-Character-Sheet#1]
given the fact characters on obsidianportal are more or less exactly one textarea of WYSIWYG rich text, how do i actually use this?

**Comment by tinwatchman** [comment]
You can use this on [Obsidian Portal](https://www.obsidianportal.com/). When you create a character, go to the Dynamic Style Sheet dropdown and select "Responsive D&D 5e Basic Rules."

**Comment by nonchip** [comment]
so a) i did already know it's for obsidian portal, as i wrote. b) there's no dropdown. also, considering your answer sounds automated, did you read my ticket?

**Comment by tinwatchman** [comment]
:shrug: I don't know what to tell you. Ask the OP people on their forum. I
just set up this DST, they're the ones hosting it.
